
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9" />

<title>FileIce &bull; Index page</title>



<!--
	phpBB style name: Absolution
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by: Christian Bullock ( http://www.ChristianBullock.com/ )

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=forums.fileice.net';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	

	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styleswitcher.js"></script>
<script type="text/javascript" src="./forum_fn.js"></script>
<script type="text/javascript" src="./tooltip.js"></script>
<script type="text/javascript" src="./dropdown.js"></script>

<link href="print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.css?id=2&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="large.css" rel="alternate stylesheet" type="text/css" title="A++" />



<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="ie.css" />
<![endif]-->

</head>

<body id="phpbb" class="section-index ltr">


<div id="page-wrap" style="width: 1000px;">

<div id="main-sidebar"></div>
        
        <div id="main-content">

<p class="skiplink"><a href="#start_here">Skip to content</a></p>
<a id="top" name="top" accesskey="t"></a>

<div id="wrap">
    <div id="header">
	    <div id="header-left">
        
        <a href="./index.php"><img src="logo.png" width="186" height="106"></img></a>
		
		</div><!-- /header-left-->
		<div id="header-right">
		    <div id="header-search-box">
			    
			</div><!--/formbox / search-box-->
		</div><!--/header-right-->
	</div><!-- /header-->
	<div class="float-left breadcrumbs"><img src="house.png" width="16" height="16" alt="" />
	    <a href="./index.php" accesskey="h">Board index</a> 
	</div><!-- /float-left / breadcrumbs -->
	
	<div class="float-right">
	    
		<span class="breadcrumbs"><img src="font_add.png" width="16" height="16" alt="" /> <a href="#" onclick="fontsizeup(); return false;" onkeypress="return fontsizeup(event);" title="Change font size">Change font size</a> &nbsp;</span>
	</div>
	<div class="clear-both" style="margin-bottom: 6px;"></div>

	
	
	
	
	<div class="toolbar">
	    <div class="toolbar-left">
		    
        </div><!-- /toolbar-left -->
        <div class="toolbar-right">
	        <img src="help.png" width="16" height="16" alt="" /> <a href="./faq.php" title="Frequently Asked Questions">FAQ</a>
            
            <img src="disconnect.png" width="16" height="16" alt="" /> <a href="./ucp.php?mode=logout&amp;sid=3fceef9f30d9190a70b0322d84390d78" title="Logout [ Alexa [Bot] ]" accesskey="x">Logout [ Alexa [Bot] ]</a>
        </div><!-- /toolbar-right -->
    </div><!-- /toolbar -->
	
	<div class="clear-both"></div>

	<a name="start_here"></a>
	<div id="page-body">
	

	

<p class="right rightside">Last visit was: Thu Nov 10, 2011 1:38 pm</p>
<p>It is currently Thu Nov 10, 2011 1:38 pm</p>
			<div class="inner">
			<ul class="topiclist">
				<li class="header">
                <div class="custom-cat-header">
                <div class="custom-cat-header-left">
                <div class="custom-cat-header-right">
                </div>
					<dl class="icon">
                    

                    
						<dd><div style="padding-left: 20px; margin-top: 8px; font-weight: bold;"><a href="./viewforum.php?f=23">Chat</a></div></dd>
					</dl>
                    </div> <!-- /custom-cat-header-left -->
                    </div> <!-- custom cat header -->
                    
				</li>
			</ul>    <div class="custom-row">


			<ul class="topiclist forums">
	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_link.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./chat/" class="forumtitle">FileIce Forum Chatroom</a><br />
					<span class="forum-descriptions"></span>
					
				</dt>
				
			</dl>
		</li>

	
			</ul>

	</div> <!-- end custom row -->

<div class="custom-foot"><div class="custom-foot-left"></div><div class="custom-foot-right"></div></div>
		</div>
	
			<div class="inner">
			<ul class="topiclist">
				<li class="header">
                <div class="custom-cat-header">
                <div class="custom-cat-header-left">
                <div class="custom-cat-header-right">
                </div>
					<dl class="icon">
                    

                    
						<dd><div style="padding-left: 20px; margin-top: 8px; font-weight: bold;"><a href="./viewforum.php?f=3">Information</a></div></dd>
					</dl>
                    </div> <!-- /custom-cat-header-left -->
                    </div> <!-- custom cat header -->
                    
				</li>
			</ul>    <div class="custom-row">


			<ul class="topiclist forums">
	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_link.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./rules.php" class="forumtitle">Forum Rules &amp; Community Guidelines</a><br />
					<span class="forum-descriptions"></span>
					
				</dt>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=6" class="forumtitle">News and Announcements</a><br />
					<span class="forum-descriptions">Important news and announcements from the FileIce team.</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">Prince</span>
						<br />Thu Nov 10, 2011 8:40 am</span>
					</dd>
					<dd class="topics">12<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">163<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=21" class="forumtitle">Official FileIce Contests</a><br />
					<span class="forum-descriptions">Official contests created by FileIce staff.</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #009900;" class="username-coloured">Bok1ca</span>
						<br />Thu Nov 10, 2011 2:11 am</span>
					</dd>
					<dd class="topics">1<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">120<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=7" class="forumtitle">Success Stories</a><br />
					<span class="forum-descriptions">Show off how much you've earned or share your stories of success with FileIce!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #FF6600;" class="username-coloured">Atlanta</span>
						<br />Thu Nov 10, 2011 5:03 am</span>
					</dd>
					<dd class="topics">159<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">1542<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=8" class="forumtitle">Introductions</a><br />
					<span class="forum-descriptions">Take a moment to introduce yourself to the rest of the FileIce community!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">BucksMaker</span>
						<br />Mon Nov 07, 2011 6:45 pm</span>
					</dd>
					<dd class="topics">111<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">711<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=9" class="forumtitle">Suggestions</a><br />
					<span class="forum-descriptions">If you have suggestion for us to improve our website or forum, let us know here!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">Riggs</span>
						<br />Wed Nov 09, 2011 2:41 am</span>
					</dd>
					<dd class="topics">89<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">689<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	
			</ul>

	</div> <!-- end custom row -->

<div class="custom-foot"><div class="custom-foot-left"></div><div class="custom-foot-right"></div></div>
		</div>
	
			<div class="inner">
			<ul class="topiclist">
				<li class="header">
                <div class="custom-cat-header">
                <div class="custom-cat-header-left">
                <div class="custom-cat-header-right">
                </div>
					<dl class="icon">
                    

                    
						<dd><div style="padding-left: 20px; margin-top: 8px; font-weight: bold;"><a href="./viewforum.php?f=4">Help &amp; Support</a></div></dd>
					</dl>
                    </div> <!-- /custom-cat-header-left -->
                    </div> <!-- custom cat header -->
                    
				</li>
			</ul>    <div class="custom-row">


			<ul class="topiclist forums">
	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=10" class="forumtitle">Frequently Asked Questions</a><br />
					<span class="forum-descriptions">Be sure to read our Frequently Asked Questions section before posting a help or support topic, as answers to most common questions or problems will be answered here already.</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #AA0000;" class="username-coloured">Opc44</span>
						<br />Fri Jul 15, 2011 11:05 am</span>
					</dd>
					<dd class="topics">4<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">4<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=11" class="forumtitle">Technical Support</a><br />
					<span class="forum-descriptions">Have a problem? Not answered in our FAQ section? Let us know here and we'll help you out!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #AA0000;" class="username-coloured">Opc44</span>
						<br />Thu Nov 10, 2011 9:44 am</span>
					</dd>
					<dd class="topics">79<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">545<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=12" class="forumtitle">Ask a Question</a><br />
					<span class="forum-descriptions">Ask any questions you have about the website that aren't answered in our FAQ section.</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">OMGWTFISTHIS</span>
						<br />Thu Nov 10, 2011 12:38 pm</span>
					</dd>
					<dd class="topics">129<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">903<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	
			</ul>

	</div> <!-- end custom row -->

<div class="custom-foot"><div class="custom-foot-left"></div><div class="custom-foot-right"></div></div>
		</div>
	
			<div class="inner">
			<ul class="topiclist">
				<li class="header">
                <div class="custom-cat-header">
                <div class="custom-cat-header-left">
                <div class="custom-cat-header-right">
                </div>
					<dl class="icon">
                    

                    
						<dd><div style="padding-left: 20px; margin-top: 8px; font-weight: bold;"><a href="./viewforum.php?f=5">General</a></div></dd>
					</dl>
                    </div> <!-- /custom-cat-header-left -->
                    </div> <!-- custom cat header -->
                    
				</li>
			</ul>    <div class="custom-row">


			<ul class="topiclist forums">
	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=13" class="forumtitle">General Discussions / Off Topic</a><br />
					<span class="forum-descriptions">Talk about whatever you want here! (Be sure to adhere to our Forum Rules &amp; Community Guidelines though!)</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">AustinGatton</span>
						<br />Thu Nov 10, 2011 1:18 pm</span>
					</dd>
					<dd class="topics">236<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">2160<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=14" class="forumtitle">Tutorials / Methods / Guides</a><br />
					<span class="forum-descriptions">Post any methods or guides you'd like to share to help other uploaders earn more!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">OMGWTFISTHIS</span>
						<br />Thu Nov 10, 2011 1:14 pm</span>
					</dd>
					<dd class="topics">79<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">1028<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=18" class="forumtitle">Joint Ventures</a><br />
					<span class="forum-descriptions">Post and browse joint ventures here. Team up with your fellow affiliates for a common goal!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">Wiseone</span>
						<br />Thu Nov 10, 2011 4:50 am</span>
					</dd>
					<dd class="topics">27<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">164<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	

		<li class="row">
			<dl class="icon" style="background-image: url(forum_read_subforum.gif); background-repeat: no-repeat;">
				<dt title="No unread posts">
                
                
					<a href="./viewforum.php?f=15" class="forumtitle">Graphics</a><br />
					<span class="forum-descriptions">Show off your latest graphic designs, hold graphics contests, and more in this section!</span>
					
				</dt>
				
                <dd class="lastpost"><span>
                    	Last post by <span style="color: #000000;" class="username-coloured">dvLden</span>
						<br />Tue Nov 01, 2011 7:26 pm</span>
					</dd>
					<dd class="topics">25<br /><span>Topics</span><dfn>Topics</dfn></dd>
					<dd class="posts">259<br /><span>Posts</span><dfn>Posts</dfn></dd>
				
			</dl>
		</li>

	
			</ul>

         <!-- end custom row -->
			</div><div class="custom-foot"><div class="custom-foot-left"></div><div class="custom-foot-right"></div></div>
	
<div class="stat-info" style="background-image: url('who-is-online.png');">
	<h3>Who is online</h3>
	<p>In total there are <strong>7</strong> users online :: 6 registered, 0 hidden and 1 guest (based on users active over the past 5 minutes)<br />Most users ever online was <strong>26</strong> on Wed Oct 05, 2011 2:49 pm<br /> <br />Registered users: <span style="color: #9E8DA7;" class="username-coloured">Alexa [Bot]</span>, <span style="color: #000000;" class="username-coloured">cvrlecd</span>, <span style="color: #9E8DA7;" class="username-coloured">Google [Bot]</span>, <span style="color: #000000;" class="username-coloured">patomica</span>, <span style="color: #000000;" class="username-coloured">Prince</span>, <span style="color: #000000;" class="username-coloured">saleee</span>
	<br /><strong>Legend: <span style="color:#AA0000">Administrators</span>, <span style="color:#0000FF">Elite Earner</span>, <span style="color:#009900">Global moderators</span>, <span style="color:#FF6600">VIP</span></strong></p>
</div>

<div class="stat-info" style="background-image: url('statistics.png');">
	<h3>Statistics</h3>
	<p>Total posts <strong>9891</strong> &bull; Total topics <strong>1245</strong> &bull; Total members <strong>918</strong> &bull; Our newest member <strong><span style="color: #000000;" class="username-coloured">Prince</span></strong></p>
</div>
</div>

<div id="page-footer">

<div class="toolbar-footer">
<div class="toolbar-left" style="padding-top: 5px; height: 31px;">
<div class="float-left"><img src="house.png" width="16" height="16" alt="" /> <a href="./index.php" accesskey="h">Board index</a><!-- If you don't agree to leave the style copyright in place, don't use this style  -->

<br />&copy; Absolution by Christian Bullock</div></div>

<!-- End of copyright notice -->

<div class="float-right toolbar-bottom-right"><div class="toolbar-right" style="padding-top: 5px; height: 31px; padding-right: 5px;">All times are UTC <br />

<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

Powered by <a href="http://www.phpbb.com/">phpBB</a>
</div>
</div><!-- /float-right -->
</div><!-- /footer-toolbar-->




		

</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	
</div>

</div> <!-- /#page-content -->


	<div id="secondary-sidebar"></div>
    </div> <!-- /#page-wrap -->
    </div>
 </body>
</html>