
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-gb" xml:lang="en-gb">
<head>

<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="en-gb" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9" />

<title>FileIce &bull; Information</title>



<!--
	phpBB style name: Absolution
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by: Christian Bullock ( http://www.ChristianBullock.com/ )

	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->

<script type="text/javascript">
// <![CDATA[
	var jump_page = 'Enter the page number you wish to go to:';
	var on_page = '';
	var per_page = '';
	var base_url = '';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '; path=/; domain=forums.fileice.net';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	

	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>
<script type="text/javascript" src="./styleswitcher.js"></script>
<script type="text/javascript" src="./forum_fn.js"></script>
<script type="text/javascript" src="./tooltip.js"></script>
<script type="text/javascript" src="./dropdown.js"></script>

<link href="./print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="./style.css?id=2&amp;lang=en" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="./normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="./medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="./large.css" rel="alternate stylesheet" type="text/css" title="A++" />



<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="./ie.css" />
<![endif]-->

</head>

<body id="phpbb" class="section-viewforum ltr">


<div id="page-wrap" style="width: 1000px;">

<div id="main-sidebar"></div>
        
        <div id="main-content">

<p class="skiplink"><a href="#start_here">Skip to content</a></p>
<a id="top" name="top" accesskey="t"></a>

<div id="wrap">
    <div id="header">
	    <div id="header-left">
        
        <a href="./index.php"><img src="logo.png" width="186" height="106"></img></a>
		
		</div><!-- /header-left-->
		<div id="header-right">
		    <div id="header-search-box">
			    
			</div><!--/formbox / search-box-->
		</div><!--/header-right-->
	</div><!-- /header-->
	<div class="float-left breadcrumbs"><img src="./house.png" width="16" height="16" alt="" />
	    <a href="./index.php" accesskey="h">Board index</a> 
	</div><!-- /float-left / breadcrumbs -->
	
	<div class="float-right">
	    
		<span class="breadcrumbs"><img src="./font_add.png" width="16" height="16" alt="" /> <a href="#" onclick="fontsizeup(); return false;" onkeypress="return fontsizeup(event);" title="Change font size">Change font size</a> &nbsp;</span>
	</div>
	<div class="clear-both" style="margin-bottom: 6px;"></div>

	
	
	
	
	<div class="toolbar">
	    <div class="toolbar-left">
		    
        </div><!-- /toolbar-left -->
        <div class="toolbar-right">
	        <img src="./help.png" width="16" height="16" alt="" /> <a href="./faq.php" title="Frequently Asked Questions">FAQ</a>
            
            <img src="./disconnect.png" width="16" height="16" alt="" /> <a href="./ucp.php?mode=logout&amp;sid=78a230dfe3764bc8813711a6cb40ea6c" title="Logout [ Alexa [Bot] ]" accesskey="x">Logout [ Alexa [Bot] ]</a>
        </div><!-- /toolbar-right -->
    </div><!-- /toolbar -->
	
	<div class="clear-both"></div>

	<a name="start_here"></a>
	<div id="page-body">
	

	

<div class="panel" id="message">
	<div class="inner"><span class="corners-top"><span></span></span>
	<h2>Information</h2>
	<p>The forum you selected does not exist.</p>
	
	<span class="corners-bottom"><span></span></span></div>
</div>

</div>

<div id="page-footer">

<div class="toolbar-footer">
<div class="toolbar-left" style="padding-top: 5px; height: 31px;">
<div class="float-left"><img src="./house.png" width="16" height="16" alt="" /> <a href="./index.php" accesskey="h">Board index</a><!-- If you don't agree to leave the style copyright in place, don't use this style  -->

<br />&copy; Absolution by Christian Bullock</div></div>

<!-- End of copyright notice -->

<div class="float-right toolbar-bottom-right"><div class="toolbar-right" style="padding-top: 5px; height: 31px; padding-right: 5px;">All times are UTC <br />

<!--
	We request you retain the full copyright notice below including the link to www.phpbb.com.
	This not only gives respect to the large amount of time given freely by the developers
	but also helps build interest, traffic and use of phpBB3. If you (honestly) cannot retain
	the full copyright we ask you at least leave in place the "Powered by phpBB" line, with
	"phpBB" linked to www.phpbb.com. If you refuse to include even this then support on our
	forums may be affected.

	The phpBB Group : 2006
//-->

Powered by <a href="http://www.phpbb.com/">phpBB</a>
</div>
</div><!-- /float-right -->
</div><!-- /footer-toolbar-->




		

</div>

</div>

<div>
	<a id="bottom" name="bottom" accesskey="z"></a>
	
</div>

</div> <!-- /#page-content -->


	<div id="secondary-sidebar"></div>
    </div> <!-- /#page-wrap -->
    </div>
 </body>
</html>